import Foundation
import GenesyxCore

/// The bundled Learn articles. The first sixteen came verbatim from the Android source of truth
/// (`docs/learn/articles.json`, commit ac59b3a); the `w*` series below is the twelve-week run.
/// Content is compiled into the app.
/// CTAs here are all tab jumps (no `.openArticle`), so `init?` always succeeds → `!` is safe.
///
/// Articles carrying a `publishedAt` are shipped in this build and revealed on that date — see
/// `LearnLibrary.published(asOf:)`. Dates are Sundays, because the Learn nudge fires Sunday 09:00
/// (`NotificationPlanner.learnWeekday`), so each piece is live nine hours before the notification
/// that announces it. Slipping the release does not break the run: everything already due simply
/// appears on first launch.
let learnArticles: [LearnArticle] = [

    LearnArticle(
        id: "a1",
        slug: "getting-started-first-week",
        title: "Your first week with Genesyx",
        excerpt: "What to do on day one, day three, and day seven — and what to ignore until later.",
        body: [
            .paragraph("The first week isn't about completeness. It's about proving to yourself that this takes a minute, not an evening."),
            .heading("Day one"),
            .paragraph("Set your cycle, then log once. That's it. The log can be almost empty — a mood and nothing else is a real entry."),
            .heading("Days two and three"),
            .paragraph("Notice how little time it takes. Most people spend under thirty seconds. If you're spending longer, you're logging more than you need to."),
            .heading("Day seven"),
            .paragraph("Your first patterns appear. They will also be mostly noise — seven days is not enough to conclude anything, and the app will say so. Look anyway. Seeing your own week written down is the point."),
            .heading("What to ignore for now"),
            .bulletList([
                "Perfect streaks. Missing a day costs you almost nothing.",
                "Every optional field. Fill in what you notice, skip what you don't.",
                "Comparing your numbers to anyone else's.",
            ]),
            .callout("If you only do one thing this week: log on the day you feel worst. That's the entry you'll be glad to have in three months."),
        ],
        category: .gettingStarted,
        tags: ["onboarding", "basics", "getting started"],
        readingTime: "5 min read",
        heroImage: "learn_hero_first_week",
        featured: true,
        relatedArticleIds: ["a2", "a9"],
        cta: ArticleCta(type: .openLog, label: "Open today's log")!,
        disclaimerRequired: false
    ),

    LearnArticle(
        id: "a2",
        slug: "why-logging-beats-remembering",
        title: "Why logging beats remembering",
        excerpt: "Memory rewrites the past to fit the present. A log doesn't.",
        body: [
            .paragraph("Memory is reconstructive. You don't replay the past — you rebuild it, every time, out of whatever material is nearest to hand. And the nearest material is how you feel right now."),
            .paragraph("This is why \"I felt terrible all week\" is so often untrue. You felt terrible today, and today has quietly colonised the other six days."),
            .heading("What a log actually does"),
            .paragraph("It's not a diary and it's not a report card. It's a set of small, boring, unrevised facts written by someone who didn't yet know how the story ended — you, on a Tuesday."),
            .heading("Boring entries beat detailed ones"),
            .bulletList([
                "A one-tap mood, logged for sixty days, is worth more than a paragraph logged four times.",
                "The entries you'll want later are the ordinary ones. Extremes you remember anyway.",
                "\"Nothing to report\" is data. Log it.",
            ]),
            .callout("The goal isn't a complete record. It's a record honest enough to disagree with you."),
        ],
        category: .tracking,
        tags: ["tracking", "habits", "basics", "memory"],
        readingTime: "4 min read",
        heroImage: "learn_hero_logging",
        featured: false,
        relatedArticleIds: ["a3", "a8"],
        cta: ArticleCta(type: .openLog, label: "Log how you feel today")!,
        disclaimerRequired: false
    ),

    LearnArticle(
        id: "a3",
        slug: "what-to-log",
        title: "Symptoms and meals: what's worth writing down",
        excerpt: "You don't need to log everything. Here's the short list.",
        body: [
            .paragraph("The completeness trap goes like this: you decide to track properly, you build an elaborate routine, you sustain it for nine days, and then you stop entirely. A smaller habit you keep beats a thorough one you abandon."),
            .heading("Worth logging daily"),
            .bulletList([
                "Mood — one tap, no elaboration.",
                "Energy — the thing you'll most want to correlate later.",
                "Anything unusual. If you noticed it, write it.",
                "Whether you ate roughly normally. Not what. Whether.",
            ]),
            .heading("Worth logging weekly"),
            .bulletList([
                "Sleep, in broad strokes — good week, bad week.",
                "Anything that changed: new medication, travel, illness, unusual stress.",
            ]),
            .heading("Not worth logging at all"),
            .paragraph("Anything you'd only be recording to feel virtuous about recording it. If you can't imagine a question it would help answer, skip it."),
            .callout("Consistency beats detail. It isn't close."),
        ],
        category: .tracking,
        tags: ["tracking", "symptoms", "nutrition", "logging"],
        readingTime: "4 min read",
        heroImage: "learn_hero_what_to_log",
        featured: false,
        relatedArticleIds: ["a2", "a9"],
        cta: ArticleCta(type: .openLog, label: "Open today's log")!,
        disclaimerRequired: false
    ),

    LearnArticle(
        id: "a4",
        slug: "hydration-basics",
        title: "Hydration, without the eight-glass myth",
        excerpt: "Where \"eight glasses a day\" came from, and what to do instead.",
        body: [
            .paragraph("The eight-glasses rule appears to trace back to a 1945 recommendation that adults need roughly 2.5 litres of water a day. The very next sentence noted that most of it already comes from food. That sentence got dropped, and the number outlived it."),
            .heading("What's actually true"),
            .bulletList([
                "For most healthy adults, thirst is a reasonable guide.",
                "Food contributes a real share of your water. Fruit, vegetables, soup, and yoghurt all count.",
                "Tea and coffee count too. The idea that they dehydrate you doesn't survive contact with the evidence at normal intake.",
                "Needs vary with heat, altitude, exercise, illness, and pregnancy. A fixed target can't account for any of that.",
            ]),
            .heading("Something more useful than a number"),
            .paragraph("Anchor water to things you already do. A glass with each meal. A glass when you sit down at your desk. This works because it removes the decision, and decisions are what habits die of."),
            .callout("Persistent, unusual thirst — especially alongside fatigue or frequent urination — is worth mentioning to a doctor. It's not something to solve by drinking more."),
        ],
        category: .nutrition,
        tags: ["hydration", "nutrition", "myths", "water"],
        readingTime: "3 min read",
        heroImage: "learn_hero_hydration",
        featured: false,
        relatedArticleIds: ["a5", "a9"],
        cta: ArticleCta(type: .openTrack, label: "Track today's water")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "a5",
        slug: "eating-with-your-cycle",
        title: "Eating with your cycle, not against it",
        excerpt: "What changes across the four phases — and what genuinely doesn't.",
        body: [
            .paragraph("Your appetite, energy, and cravings genuinely do shift across a cycle. That much is well established. What's less well established is almost everything else you'll read about it online."),
            .paragraph("So here's an honest version: a short list of what actually changes, a shorter list of what to do about it, and a clear note about the claims that don't hold up."),
            .heading("What actually shifts"),
            .bulletList([
                "Iron. Menstruation loses iron. Foods rich in it — lentils, dark leafy greens, red meat — are worth leaning on during your period.",
                "Energy. Many people feel steadier in the follicular phase and flatter in the late luteal phase. Eating regularly matters more than eating perfectly.",
                "Appetite. A modest increase in the luteal phase is normal and well documented. It is not a failure of discipline.",
            ]),
            .heading("What doesn't"),
            .paragraph("Your cycle length, your ovulation timing, and the sex of any future child are not influenced by what you eat. No food, supplement, or eating pattern changes them. Claims otherwise are common, confidently stated, and unsupported."),
            .callout("If an article promises that a food will change your cycle or influence conception, that's the moment to close the tab."),
            .heading("A practical idea per phase"),
            .bulletList([
                "Period — iron with a source of vitamin C alongside it, which helps absorption.",
                "Follicular — you likely have energy. This is a good week for meals that take effort.",
                "Ovulatory — nothing special is required. Keep eating.",
                "Luteal — more frequent, smaller meals help some people with energy dips. Try it, keep it if it works, drop it if it doesn't.",
            ]),
            .paragraph("That last instruction applies to this whole article. Log how you feel, look back after a couple of cycles, and keep only what your own data supports."),
        ],
        category: .nutrition,
        tags: ["nutrition", "cycle", "phases", "food"],
        readingTime: "6 min read",
        heroImage: "learn_hero_eating_cycle",
        featured: false,
        relatedArticleIds: ["a4", "a6"],
        cta: ArticleCta(type: .openNutrition, label: "See this phase's foods")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "a6",
        slug: "gentle-guide-supplements",
        title: "A gentle guide to supplements",
        excerpt: "What the evidence supports, what it doesn't, and why to talk to someone first.",
        body: [
            .paragraph("The word supplement is doing a lot of quiet work. It means: in addition to. Not instead of, and not as insurance against, a diet that's already broadly fine."),
            .heading("The one with strong consensus"),
            .paragraph("Folate — folic acid in its supplement form — is recommended by mainstream health bodies for anyone who might become pregnant, ideally starting before conception. The evidence for reduced neural tube defects is unusually strong. This is the one worth raising with a doctor or pharmacist rather than reading about."),
            .heading("Everything else: ask, don't assume"),
            .paragraph("Vitamin D, omega-3, zinc, and the rest all have a real evidence base for specific people in specific circumstances — and a much larger marketing base aimed at everyone else. Whether any of them is useful for you depends on your diet, your bloodwork, where you live, and what else you take."),
            .paragraph("We're deliberately naming no doses and no brands here. A dose that's sensible for one person is pointless or harmful for another, and that judgement needs someone who can see your actual situation."),
            .heading("Interactions are real"),
            .paragraph("Supplements interact with medication and with each other. Some affect how other things are absorbed. \"Natural\" carries no information about safety."),
            .heading("How to raise it"),
            .paragraph("A pharmacist is free to talk to, knows about interactions, and doesn't need an appointment. Bring a list of everything you take, including anything you'd think of as \"just a vitamin\". That's usually the whole conversation."),
            .callout("If you're taking prescription medication, check before starting anything new. This is the single highest-value thing in this article."),
        ],
        category: .nutrition,
        tags: ["supplements", "nutrition", "folate", "evidence"],
        readingTime: "6 min read",
        heroImage: "learn_hero_supplements",
        featured: false,
        relatedArticleIds: ["a5", "a4"],
        cta: ArticleCta(type: .openLog, label: "Log how you're feeling")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "a7",
        slug: "what-insights-mean",
        title: "What \"insights\" actually means",
        excerpt: "Your app can spot correlations. It cannot spot causes. That distinction is the whole game.",
        body: [
            .paragraph("An insight in this app is a pattern found by comparing things you logged. Nothing more mystical than that, and nothing more authoritative either."),
            .heading("Correlation, concretely"),
            .paragraph("Suppose your logs show low energy on the days you slept badly. Three explanations fit equally well: bad sleep drained you; whatever drained you also wrecked your sleep; or a third thing — illness, stress, a hard week — caused both. The data cannot distinguish between them. Only you can, and only sometimes."),
            .heading("How much data is enough"),
            .bulletList([
                "Three weeks: almost nothing. Treat every pattern as coincidence.",
                "Three months: something. Patterns that survive this long are worth noticing.",
                "A year: enough to see how you change across seasons and circumstances.",
            ]),
            .heading("Holding an insight lightly"),
            .paragraph("A good insight makes you curious, not certain. If reading one makes you want to change three things at once, that's a sign you've believed it too hard."),
        ],
        category: .insights,
        tags: ["insights", "data", "basics", "correlation"],
        readingTime: "5 min read",
        heroImage: "learn_hero_insights",
        featured: false,
        relatedArticleIds: ["a8", "a10"],
        cta: ArticleCta(type: .openInsights, label: "See your insights")!,
        disclaimerRequired: false
    ),

    LearnArticle(
        id: "a8",
        slug: "reading-your-trends",
        title: "Reading your trends without over-reading them",
        excerpt: "One bad day is noise. Six weeks is a signal. Here's how to tell.",
        body: [
            .paragraph("Bodies vary. Not as a failure of the body, but as a basic property of it. Two days with identical sleep, food, and stress will still produce different numbers, and nothing has gone wrong."),
            .heading("What noise looks like"),
            .bulletList([
                "A single outlier in an otherwise flat run.",
                "A dramatic value on a day something unusual happened.",
                "Any pattern you can only see if you squint.",
            ]),
            .heading("What a signal looks like"),
            .bulletList([
                "It persists across several cycles, not several days.",
                "It shows up whether or not you were looking for it.",
                "It doesn't disappear when you exclude the most dramatic week.",
            ]),
            .heading("The trap"),
            .paragraph("When you feel worse, you track harder. More tracking finds more patterns. More patterns feel like confirmation that something is wrong. This loop is worth knowing about because it feels exactly like diligence."),
            .callout("A trend that is persistent, new for you, and unexplained is worth raising with a clinician — not worth resolving alone with more data."),
        ],
        category: .insights,
        tags: ["insights", "trends", "patterns", "variance"],
        readingTime: "5 min read",
        heroImage: "learn_hero_trends",
        featured: false,
        relatedArticleIds: ["a7", "a10"],
        cta: ArticleCta(type: .openInsights, label: "See your insights")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "a9",
        slug: "small-habits-that-hold",
        title: "Small habits that hold",
        excerpt: "The habit research says: make it smaller than feels worthwhile.",
        body: [
            .paragraph("Ambitious habits fail in week two, and they fail for a structural reason: they were designed by a version of you who had unusual amounts of energy and optimism. That person does not show up on Wednesdays."),
            .heading("Anchor it to something that already happens"),
            .paragraph("You already brush your teeth. You already sit down at a desk, or on a bus. Attach the new thing to the old thing and you never have to remember it, only notice it."),
            .heading("The two-minute version"),
            .paragraph("Whatever you want to do, define a version that takes two minutes and do that. Not as a stepping stone to the real habit — as the habit. Scale later, if you want to, or don't."),
            .heading("Missing a day"),
            .paragraph("Missing one day changes nothing measurable. Missing two is the pattern worth watching, because the second miss is where the habit stops being automatic."),
            .heading("On streaks"),
            .paragraph("Streaks motivate some people and quietly torment others. If a broken streak makes you want to abandon the whole thing, the streak is costing you more than it's paying. Ignore the number."),
        ],
        category: .wellness,
        tags: ["habits", "wellness", "consistency", "routine"],
        readingTime: "4 min read",
        heroImage: "learn_hero_habits",
        featured: false,
        relatedArticleIds: ["a3", "a10"],
        cta: ArticleCta(type: .openLog, label: "Start with one log")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "a10",
        slug: "using-what-you-learn",
        title: "Using what you learn",
        excerpt: "Data is only useful if it changes something. Here's how to close the loop.",
        body: [
            .paragraph("Tracking that never changes a decision is a hobby. A pleasant one — but let's be honest about which it is."),
            .heading("The loop"),
            .bulletList([
                "Notice something in your logs.",
                "Guess at why, out loud, in one sentence.",
                "Change exactly one thing.",
                "Wait a full cycle. Not a week.",
                "Look again.",
            ]),
            .heading("Why one thing"),
            .paragraph("Change three things and you've learned nothing, whatever the result. You won't know which one moved the needle, or whether two of them cancelled out. This is the single most common way people waste months of careful tracking."),
            .heading("When to stop experimenting"),
            .paragraph("If something is getting worse, or it's new, or it frightens you, stop running experiments and talk to a professional. Your logs will make that conversation better. They are not a substitute for it."),
            .callout("Bring your logs to the appointment. \"Here's six weeks of data\" is a much better opening than \"I've been feeling off.\""),
        ],
        category: .insights,
        tags: ["insights", "decisions", "wellness", "experiments"],
        readingTime: "4 min read",
        heroImage: "learn_hero_using",
        featured: false,
        relatedArticleIds: ["a7", "a8"],
        cta: ArticleCta(type: .openInsights, label: "See your insights")!,
        disclaimerRequired: true
    ),

    // MARK: - Guides (in-app how-to manuals)

    LearnArticle(
        id: "g1",
        slug: "guide-vaginal-ph-tracker",
        title: "Using the vaginal pH tracker",
        excerpt: "How to read a pH strip, match it to a value, and log it so your trend is honest.",
        body: [
            .heading("What this feature is for"),
            .paragraph("The vaginal pH tracker turns a paper pH strip into a trend you can actually use. A single reading tells you almost nothing — a strip read once is a moment, not a pattern. The tracker holds your readings over weeks so you can see whether your vaginal pH sits in its typical range (about 3.8–4.5) over time, and whether anything shifts it — it varies naturally across your cycle."),
            .paragraph("Genesyx does not sell strips. Any standard pH test strip from a pharmacy works, as long as it reads across the range the app accepts."),
            .heading("How to use it"),
            .bulletList([
                "Use the strip exactly as its packaging instructs, and read it within the time the instructions state.",
                "Match the colour pad on the strip to the colour chart that came with it. Note the number it points to (e.g. 4.2).",
                "Open the pH tab and tap \"Log pH\".",
                "Move the slider to the value on your strip, or use the ± buttons. The app rounds to one decimal place.",
                "Pick the time you took the reading (it defaults to now), add a note if you want, and Save.",
            ]),
            .heading("For a trend you can trust"),
            .bulletList([
                "Log at a similar point in your routine each time, and note your cycle day alongside it — vaginal pH shifts naturally through the cycle, so that context makes the trend readable.",
                "One reading a week is enough to see a trend over a couple of months. More is fine, but not required.",
                "If a strip looks like it didn't read properly, read it again rather than saving a doubtful value.",
            ]),
            .heading("When to speak to someone"),
            .paragraph("If your readings stay above the typical healthy range over several days, or a pattern worries you, a GP, nurse, or pharmacist can talk it through with you. This tracker is a record for your own use — it isn't a diagnosis."),
            .heading("Conclusion"),
            .paragraph("The tracker is a low-effort, weekly habit that turns a paper strip into a real trend. Log once a week, note your cycle day, and let the app hold the history. Don't chase a single number — chase the pattern."),
        ],
        category: .guides,
        tags: ["guide", "ph", "vaginal ph", "how to"],
        readingTime: "4 min read",
        heroImage: "learn_hero_insights",
        featured: false,
        relatedArticleIds: ["g3", "g6", "a4"],
        cta: ArticleCta(type: .openPh, label: "Open the pH tracker")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "g2",
        slug: "guide-how-the-log-works",
        title: "How the daily log works",
        excerpt: "What to log, what to skip, and why a boring one-tap entry beats a detailed one you abandon.",
        body: [
            .heading("What this feature is for"),
            .paragraph("The daily log is the heart of Genesyx. It's a short, honest record of how today went — written by a version of you who didn't yet know how the story ends. Memory rewrites the past to fit how you feel today; a log doesn't. That's the whole point."),
            .heading("How to use it"),
            .bulletList([
                "Tap \"Log today\" on Home, or \"Add to today's log\" on Track.",
                "Everything is optional. Tap a mood, an energy level, any symptoms you noticed.",
                "Add a custom symptom if yours isn't listed — type it once and it's there next time.",
                "Tap sleep, water, or supplements to adjust those if you want — or skip them entirely.",
                "Add a note if something specific happened (new medication, travel, illness, stress).",
                "Tap \"Save log\". It saves on your device straight away and closes — even with no signal. If you're offline, it syncs by itself the next time you're connected, so nothing is lost.",
            ]),
            .heading("What's worth logging"),
            .bulletList([
                "Mood — one tap, no elaboration.",
                "Energy — the thing you'll most want to correlate later.",
                "Anything unusual. If you noticed it, write it.",
                "\"Nothing to report\" is a real entry. Log it.",
            ]),
            .heading("Benefits if you use it"),
            .paragraph("A one-tap mood logged for sixty days is worth more than a paragraph logged four times. The entries you'll want later are the ordinary ones — extremes you remember anyway. After a few cycles, your Insights tab starts to surface patterns: energy dips in the luteal phase, symptoms that cluster, hydration that slips on certain days. None of that exists without the boring, consistent log."),
            .heading("Conclusion"),
            .paragraph("Log in under a minute, most days. Skip what you don't notice. The goal isn't a complete record — it's a record honest enough to disagree with you later. That's the habit that makes every other feature in the app work."),
        ],
        category: .guides,
        tags: ["guide", "log", "how to", "basics"],
        readingTime: "4 min read",
        heroImage: "learn_hero_logging",
        featured: false,
        relatedArticleIds: ["a2", "a3", "g5"],
        cta: ArticleCta(type: .openLog, label: "Open today's log")!,
        disclaimerRequired: false
    ),

    LearnArticle(
        id: "g3",
        slug: "guide-how-to-log-ph",
        title: "How to log a pH reading",
        excerpt: "The exact taps to record a vaginal pH value, and how to keep your readings comparable.",
        body: [
            .heading("What this feature is for"),
            .paragraph("Logging a pH reading is how you feed the vaginal pH tracker. Each reading you save becomes a point on your trend chart and feeds your 7- and 30-day averages on Insights. The log screen rounds your value to one decimal place and keeps it within the scale the app accepts, so you can't accidentally save a misread strip."),
            .heading("How to use it"),
            .bulletList([
                "Open the pH tab and find the \"Vaginal pH\" card.",
                "Tap \"Log pH\".",
                "Move the slider to your strip's value, or use the ± buttons (each step is 0.1).",
                "The big number and its colour update live — healthy (up to 4.5) or elevated (above 4.5).",
                "If you want, change the time — useful if you're logging a reading you took earlier today.",
                "Add a note if something was different (e.g. \"day 12 of my cycle\").",
                "Tap \"Save\". The reading stores on your device immediately and syncs to your account if you're signed in.",
            ]),
            .heading("Editing or deleting"),
            .paragraph("To fix a mistake, open the pH card, tap the latest reading, and edit or delete it. Deletions are tombstoned — marked deleted rather than removed — so the change syncs safely if you're signed in."),
            .heading("Benefits if you use it"),
            .paragraph("Each reading adds to a trend you can actually read. After a few weeks, the Insights pH card shows your current value with a status colour, a trend arrow (up, down, or flat vs your previous reading), and 7- and 30-day averages. That's a real signal — not a single number in isolation. It's also something concrete to bring to a clinician if a pattern persists."),
            .heading("Conclusion"),
            .paragraph("Log once a week at a similar point in your routine, noting your cycle day. The slider makes it a ten-second task. Let the app hold the history and do the math — your job is just the consistent tap."),
        ],
        category: .guides,
        tags: ["guide", "ph", "how to", "vaginal ph"],
        readingTime: "3 min read",
        heroImage: "learn_hero_hydration",
        featured: false,
        relatedArticleIds: ["g1", "g6", "a7"],
        cta: ArticleCta(type: .openPh, label: "Log a pH reading")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "g4",
        slug: "guide-nutrition-focus",
        title: "How your nutrition focus works",
        excerpt: "Why your focus foods change through your cycle, and what to actually do with them.",
        body: [
            .heading("What this feature is for"),
            .paragraph("Nutrition focus is phase-aware food guidance. As you move through your cycle — period, follicular, ovulatory, luteal — your body's needs shift slightly. The Nutrition tab shows focus foods and a short rationale tuned to whichever phase you're in, so you're not eating from a static list. It's gentle and specific, not a diet."),
            .heading("How to use it"),
            .bulletList([
                "Make sure your cycle is set up (Home → set your last period start). Without it, the tab can't pick a phase.",
                "Open the Nutrition tab. The header shows today's phase.",
                "The \"Focus foods\" card lists a few foods worth leaning into this phase, each with a short reason. Tap one to expand and see more detail.",
                "The supplement plan card shows the evidence-informed essentials (folate, omega-3, vitamin D, zinc) — review it any time.",
                "The \"Learn more\" section links to real nutrition articles; \"See all articles\" jumps to the full Learn library.",
            ]),
            .heading("What it does and doesn't claim"),
            .paragraph("Your appetite, energy, and cravings genuinely shift across a cycle — that's well established. But no food, supplement, or eating pattern changes your cycle length, your ovulation timing, or the sex of a future child. Claims otherwise are common, confidently stated, and unsupported. The focus foods are about working with your cycle, not manipulating it."),
            .heading("Benefits if you use it"),
            .paragraph("Instead of a generic fertility diet, you get small, doable, phase-appropriate shifts — iron-rich foods during your period, steady energy in the follicular phase, smaller frequent meals if luteal energy dips. It removes the guesswork without overwhelming you. Over a couple of cycles, you'll notice which foods actually help you feel steady, and keep only what your own data supports."),
            .heading("Conclusion"),
            .paragraph("Check Nutrition when you change phase, not every day. Pick one focus food to lean into, keep it if it works, drop it if it doesn't. The point is steady, phase-aware eating — not perfection."),
        ],
        category: .guides,
        tags: ["guide", "nutrition", "how to", "cycle"],
        readingTime: "4 min read",
        heroImage: "learn_hero_eating_cycle",
        featured: false,
        relatedArticleIds: ["a5", "a6", "g5"],
        cta: ArticleCta(type: .openNutrition, label: "See this phase's foods")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "g5",
        slug: "guide-how-hydration-works",
        title: "How the Hydration Coach works",
        excerpt: "Why the card changes through the day, and what the streak means.",
        body: [
            .heading("What this feature is for"),
            .paragraph("The Hydration Coach is a small card at the top of the Nutrition tab that helps you drink water steadily without thinking about it. It's not a nag — it's a live, time-of-day-aware nudge that tells you what to do right now. It's in-app only: no notifications, no buzzing, no permission."),
            .heading("How to use it"),
            .bulletList([
                "Open the Nutrition tab. The Hydration card sits at the top.",
                "You'll see today's water total (e.g. 0.8 / 2.4 L), a progress bar, and + / − buttons.",
                "Tap + each time you drink a glass (about 200 ml). Tap − if you over-counted.",
                "Below the number is a bold coach line naming the part of day — \"Morning — start with a glass now\" in the morning, \"Midday — a glass with lunch\" around noon, \"Evening — small sips only\" at night. It changes through the day.",
                "When you hit the 2.4 L goal, the line switches to a \"target reached\" message.",
                "A small flame shows your daily streak — consecutive days you've logged any water.",
            ]),
            .heading("Why it works this way"),
            .paragraph("The most effective hydration habit is anchoring a glass to something you already do — a glass with each meal, one at your desk. The coach line suggests an anchor based on the time of day, so the decision is already made. Decisions are what habits die of; removing them is the whole trick."),
            .heading("Benefits if you use it"),
            .paragraph("Steady hydration supports your energy and mood. The streak is there for motivation, but the app deliberately doesn't shame a broken one — missing a day costs almost nothing. The goal is consistency, not perfection."),
            .heading("Conclusion"),
            .paragraph("Tap + when you drink. Let the coach line tell you what part of day it is and what to do. Don't chase the streak — chase the steady habit. A glass anchored to a meal, most days, is the whole job."),
        ],
        category: .guides,
        tags: ["guide", "hydration", "how to", "coach"],
        readingTime: "4 min read",
        heroImage: "learn_hero_hydration",
        featured: false,
        relatedArticleIds: ["a4", "g3", "g6"],
        cta: ArticleCta(type: .openNutrition, label: "Open the Hydration Coach")!,
        disclaimerRequired: false
    ),

    LearnArticle(
        id: "g6",
        // Slug kept from when this article covered the pH card's old home on Nutrition. pH has its
        // own tab now and the piece was rewritten around the trend chart, but a slug is a route and
        // a read-history key, so it stays.
        slug: "guide-track-ph-in-nutrition",
        title: "Reading your pH trend",
        excerpt: "What the chart, the range selector, and the status colour are actually telling you.",
        body: [
            .heading("What this feature is for"),
            .paragraph("Logging a reading is the easy half. The chart on the pH tab is the half that pays you back: it holds every reading you've saved and draws the shape they make. A shape is something you can read. A single number isn't."),
            .heading("How to read the card"),
            .bulletList([
                "Open the pH tab. Your latest reading sits at the top with the date and time you took it.",
                "The colour beside it is its status — healthy up to 4.5, elevated above that.",
                "Below is the chart. The shaded bands mark the same two ranges, so you can see where each point falls without reading the axis.",
                "The range selector (7d, 30d, 90d, All) changes how much history the chart draws. It needs at least two readings in the range to draw a line.",
            ]),
            .heading("What the shape is worth"),
            .bulletList([
                "A steady band you return to is your normal. That's the useful thing to know.",
                "One point outside it is noise. Vaginal pH moves with your cycle, with your period, and with the time of day you measured.",
                "The same movement at the same point across two or three cycles is a pattern — and that is worth writing down alongside your cycle day.",
            ]),
            .heading("Where it goes next"),
            .paragraph("The Insights tab reads the same readings and adds your 7- and 30-day averages plus a trend arrow against your previous reading. Nothing is recalculated differently there — it's the same history, summarised."),
            .heading("When to speak to someone"),
            .paragraph("If your readings sit above the usual range for several days, or the pattern worries you, a GP, nurse, or pharmacist can talk it through. The chart is a record for your own use — it isn't a diagnosis."),
            .heading("Conclusion"),
            .paragraph("Log weekly, note your cycle day, and look at the 90-day view after a couple of months rather than the number after every strip. Read the shape, not the point."),
        ],
        category: .guides,
        tags: ["guide", "ph", "trends", "how to"],
        readingTime: "3 min read",
        heroImage: "learn_hero_trends",
        featured: false,
        relatedArticleIds: ["g1", "g3", "g5"],
        cta: ArticleCta(type: .openPh, label: "Open the pH tab")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "g7",
        slug: "guide-cycle-and-phases",
        title: "How your cycle and phases work",
        excerpt: "Where the phase names come from, what the app is predicting, and how much to trust it.",
        body: [
            .heading("What this feature is for"),
            .paragraph("Almost everything else in the app is built on top of your cycle. Your phase decides which focus foods Nutrition shows you, which colours the calendar draws, and when the fertile-window nudge fires. Set it up once and the rest follows. Skip it and the app can still log, but it cannot tell you where you are."),
            .heading("Setting it up"),
            .bulletList([
                "On Home, tap \"Start tracking\" on the welcome card. (It's the same editor as Profile → Health Profile, if you come back to it later.)",
                "Enter the first day of your last period. This one is required — nothing is guessed for you, and Save stays greyed out until you pick a date.",
                "Confirm your cycle length. The default is 28 days; anything from 21 to 35 is accepted.",
                "Confirm your period length. The default is 5 days; 1 to 10 is accepted.",
                "The welcome card is replaced by your phase card as soon as you save.",
            ]),
            .heading("The four phases"),
            .bulletList([
                "Period — from day 1 for as many days as you set your period length.",
                "Follicular — from the end of your period up to the day before ovulation.",
                "Ovulatory — the single predicted ovulation day.",
                "Luteal — from the day after ovulation until your next period starts.",
            ]),
            .heading("Where the predicted dates come from"),
            .paragraph("The app places ovulation 14 days before your next period is due, and draws the fertile window from five days before that day to one day after. On a 28-day cycle that puts ovulation on day 14 and the window across days 9 to 15. Change your cycle length and both move with it."),
            .paragraph("The 14-day figure is a convention, not a measurement. The luteal phase is the more consistent half of the cycle for most people, which is why the estimate is anchored there — but it is still an average applied to you, not an observation of this particular cycle."),
            .heading("Where your phase shows up"),
            .bulletList([
                "Home — the phase name, the day of your cycle, days until your next period, and your predicted ovulation day.",
                "Track — the calendar tints each day by what it is. The legend underneath names the five: Period, Fertile window, Ovulation, Luteal, Follicular. A card below it repeats your current phase in words.",
                "Nutrition — the header carries today's phase, and a card announces the day it changes.",
                "Insights — a timeline of the whole cycle with your ovulation day, your fertile window, and where today sits on it.",
                "A notification — on the morning your predicted window opens, if you've turned that one on. It is deliberately vague (\"A note about your cycle\") because a lock screen is read by whoever is holding the phone.",
            ]),
            .heading("How much to trust it"),
            .paragraph("These are predictions from your averages, so they are a starting point rather than an answer. Cycles vary, and the first month after you set the app up is the least reliable one — it has nothing but your defaults to work from. What makes it better is logging: the more of your own data sits behind the estimate, the more it describes you rather than a textbook."),
            .paragraph("This is not contraception, and it should not be used as any part of it. If your cycles are very irregular, or something changes and stays changed, a GP or nurse is the right place to take that."),
            .heading("Conclusion"),
            .paragraph("Set your last period date honestly, correct it when a period arrives early or late, and read the fertile window as a likely range rather than a date. The predictions are only ever as good as the dates you give them."),
        ],
        category: .guides,
        tags: ["guide", "cycle", "phases", "how to"],
        readingTime: "5 min read",
        heroImage: "learn_hero_fertile_window",
        featured: false,
        relatedArticleIds: ["w1", "g4", "g2"],
        cta: ArticleCta(type: .openTrack, label: "Open your calendar")!,
        disclaimerRequired: true
    ),

    LearnArticle(
        id: "g8",
        slug: "guide-sleep-tracking",
        title: "How sleep tracking works",
        excerpt: "A duration you enter yourself, what the week's chart adds up to, and what it deliberately doesn't do.",
        body: [
            .heading("What this feature is for"),
            .paragraph("Sleep here is one number a day: how long you slept. You enter it — nothing is measured, and the app never touches your phone's sensors or your watch. That sounds like a limitation and mostly isn't: a rough figure you actually record every day is worth more than a precise one you stop looking at."),
            .heading("Logging a night"),
            .bulletList([
                "Open the Track tab and find Sleep under \"Your trackers\". The row shows what you've entered for today, or a dash if you haven't entered anything, with the last seven nights sketched beside it.",
                "Tap it. The sheet opens on 7h 0m for a day you haven't logged — a starting point to nudge, not a recommendation.",
                "Set hours (up to 12) and minutes (in fives).",
                "Tap Save. Tap the row again any time to change it, or Clear to remove the entry entirely.",
                "A small badge tells you where the entry is: saved on the device, synced to your account, or waiting for a connection.",
            ]),
            .heading("What the week adds up to"),
            .bulletList([
                "The Insights tab draws this week as bars, Monday to Sunday. It is the calendar week, not your last seven nights — so on a Wednesday you'll see three bars and four empty ones waiting.",
                "Beside them: your nightly average, and \"nights logged\" out of seven.",
                "A line underneath reads the two together — how much you're averaging, over how many nights.",
            ]),
            .paragraph("The average deliberately ignores the nights you skipped rather than counting them as zero, so a missed entry lowers your \"nights logged\" and leaves the average honest. The bars for those nights are drawn flat and grey rather than left out, because a gap you can see is more useful than one you can't."),
            .heading("What it counts towards"),
            .paragraph("A night of sleep on its own is enough to make a day count as logged, so it keeps your streak alive by itself. It also feeds your weekly summary, which compares this week's average against last week's — but only when both weeks have sleep in them, because a comparison against nothing is not a comparison."),
            .heading("What it doesn't do"),
            .paragraph("There's no quality rating, no bedtime or wake time, no stages, and no attempt to relate your sleep to your cycle phase. If you want the relationship between rest, stress and your cycle, that's an article rather than a feature — the app records the hours and leaves the reading to you."),
            .heading("Conclusion"),
            .paragraph("Enter last night roughly, first thing, and don't agonise over fifteen minutes either way. Seven entries that are approximately right will tell you more about your week than two that are exact."),
        ],
        category: .guides,
        tags: ["guide", "sleep", "how to", "tracking"],
        readingTime: "3 min read",
        heroImage: "learn_hero_sleep_stress",
        featured: false,
        relatedArticleIds: ["w7", "g2", "a7"],
        cta: ArticleCta(type: .openTrack, label: "Log last night's sleep")!,
        disclaimerRequired: false
    ),

    LearnArticle(
        id: "g9",
        slug: "guide-logging-symptoms",
        title: "How to log how you feel",
        excerpt: "The daily log, what's in it, and what a month of symptoms can show you.",
        body: [
            .heading("What this feature is for"),
            .paragraph("Symptoms are the part of a cycle you notice and then forget. Logging them takes about fifteen seconds and turns \"I think I get headaches before my period\" into something you can actually check."),
            .heading("Opening the log"),
            .bulletList([
                "From Home, tap \"Log today\".",
                "Or from Track, tap \"Add to today's log\".",
                "For a day you missed, tap it in the calendar and choose \"Add a log\" — or \"Edit this day\" if something's already there. The sheet titles itself with the day so you always know which one you're writing on.",
                "Future days can't be logged. There's nothing to record about a day that hasn't happened.",
            ]),
            .heading("What's in the sheet, in order"),
            .bulletList([
                "Mood — Great, Good, Okay, or Low.",
                "Energy — Low, Normal, or High.",
                "Symptoms — headache, fatigue, cramps, nausea, bloating, acne, backache, tender breasts. Tap as many as apply; tap again to remove one.",
                "Intimacy — a single \"Sex\" chip. It is private to you: a linked partner sees your name, never your logs.",
                "Sleep, water and supplements — three small cards that open their own sheets.",
                "Notes — anything the chips don't cover.",
                "Then \"Save log\".",
            ]),
            .heading("Symptoms that aren't on the list"),
            .paragraph("Tap \"Add\" at the end of the chips and type your own. It's kept and offered alongside the standard ones from then on, so name it the way you'll recognise it — the same wording every time is what lets a pattern show up later."),
            .heading("What happens to it"),
            .bulletList([
                "The day gets a dot on the calendar, under \"Symptoms / notes\" in the legend.",
                "Insights builds a four-week view of how many symptoms you logged each day, and names the one you recorded most often with a count.",
                "Anything at all in the log keeps your daily streak going — symptoms alone are enough.",
            ]),
            .paragraph("Until you've logged something on seven separate days, Insights says \"too soon to read patterns\" rather than guessing. A pattern needs something to be a pattern across, and a confident-sounding summary drawn from three days would be worse than an honest blank."),
            .heading("What it is and isn't"),
            .paragraph("This is a record you keep, not an interpretation the app makes. Nothing here decides that a symptom belongs to a phase or means something about your health — it counts what you entered and shows you the count. That record is genuinely useful to bring to a GP appointment, where the interpreting belongs."),
            .heading("Conclusion"),
            .paragraph("Log on the bad days especially — those are the ones worth being able to look back at. Use the same words each time, and give it a month before you expect the picture to say anything."),
        ],
        category: .guides,
        tags: ["guide", "symptoms", "logging", "how to"],
        readingTime: "4 min read",
        heroImage: "learn_hero_what_to_log",
        featured: false,
        relatedArticleIds: ["g2", "a3", "a8"],
        cta: ArticleCta(type: .openLog, label: "Log how you feel today")!,
        disclaimerRequired: false
    ),

    // MARK: - The twelve-week series (shipped now, revealed weekly)
    //
    // Week 7 of the client's plan — the Shettles method — is deliberately absent. Its subject
    // cannot be written without the claim language `LearnContentTests.bannedPhrases` exists to
    // keep out of this app, and relaxing that guard is a client and medical-reviewer decision.
    // The remaining eleven run on consecutive Sundays so there is no silent week; 2026-11-08 is
    // held free for it if it is ever cleared.

    LearnArticle(
        id: "w1",
        slug: "fertile-window",
        title: "Understanding your fertile window",
        excerpt: "Six days — and the useful end of them comes before the event you are trying to catch.",
        body: [
            .paragraph("Across a whole cycle there are roughly six days when pregnancy is possible: the five leading up to ovulation, and ovulation day itself. Everything else is outside the window."),
            .paragraph("The part that surprises people is which end matters. Sperm can survive several days in fertile cervical fluid. An egg, once released, is viable for less than a day. So the window opens well before ovulation and effectively closes with it."),
            .heading("Why a predicted date is a prediction"),
            .paragraph("Your app estimates ovulation from your cycle history. That estimate is honest arithmetic, not a measurement — and ovulation is the part of the cycle that moves most. Illness, travel, a hard fortnight and a bad run of sleep can all shift it by days."),
            .paragraph("The stretch after ovulation is the steadier half. Which means a cycle that ran long usually ran long at the start, not the end."),
            .heading("Signs that come from your body rather than the calendar"),
            .bulletList([
                "Cervical fluid turning clearer, wetter and more stretchy over several days.",
                "A small sustained rise in resting temperature — which confirms ovulation has happened rather than predicting it.",
                "Ovulation tests picking up the hormone surge that precedes release by a day or so.",
            ]),
            .paragraph("None of these is a stopwatch. Read together across a couple of cycles they tell you far more than any one of them alone."),
            .callout("Treat the predicted date as the middle of a window, not a deadline. If you are only ever aiming at one day, you are aiming at the least reliable part of the estimate."),
        ],
        category: .tracking,
        tags: ["cycle", "fertile window", "ovulation", "timing"],
        readingTime: "4 min read",
        heroImage: "learn_hero_fertile_window",
        featured: false,
        relatedArticleIds: ["w4", "w6", "w8"],
        cta: ArticleCta(type: .openTrack, label: "Open your cycle")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 8, 23)
    ),

    LearnArticle(
        id: "w2",
        slug: "vaginal-ph-explained",
        title: "What your vaginal pH is actually telling you",
        excerpt: "One reading means very little. A pattern across two months means quite a lot.",
        body: [
            .paragraph("Vaginal pH is a measure of acidity. A healthy vaginal environment is acidic, and it is kept that way largely by the bacteria that live there — lactobacilli, which produce lactic acid as they go about their business."),
            .paragraph("That acidity is not a target you hit. It is a by-product of an ecosystem doing well."),
            .heading("Why a single reading tells you almost nothing"),
            .paragraph("pH shifts naturally across the cycle, and it responds to your period, to recent sex, to washing, and to the time of day you measured. One elevated number on one morning is noise until something repeats."),
            .heading("What a trend can show"),
            .bulletList([
                "Whether your readings sit in a consistent range, or move around a lot.",
                "Whether the movement lines up with a point in your cycle, which would make it a pattern rather than a surprise.",
                "Whether something you changed a month ago shows up in the numbers, or does not.",
            ]),
            .heading("What it is not"),
            .paragraph("It is not a fertility score, and it is not something to correct through diet. Food does not meaningfully move vaginal pH, and no eating pattern has been shown to change it. Anything claiming otherwise is selling you something."),
            .paragraph("If your readings sit persistently outside the usual range, or you have symptoms that bother you, that is a conversation for a clinician rather than a number to manage alone."),
            .callout("Log weekly, note the cycle day, and look at the shape after two months. One reading is a data point. Eight is a picture."),
        ],
        category: .tracking,
        tags: ["ph", "tracking", "cycle"],
        readingTime: "4 min read",
        heroImage: "learn_hero_ph_explained",
        featured: false,
        relatedArticleIds: ["g1", "g3", "w1"],
        cta: ArticleCta(type: .openPh, label: "Log a pH reading")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 8, 30)
    ),

    LearnArticle(
        id: "w3",
        slug: "nutrition-before-conception",
        title: "Eating in the months before conception",
        excerpt: "The one thing with strong evidence has a deadline, and it lands before most people start looking.",
        body: [
            .paragraph("Most preconception nutrition advice is ordinary good-eating advice repeated more urgently. There is one genuine exception, and it is worth knowing because its timing is counterintuitive."),
            .heading("Folic acid, and why the timing matters"),
            .paragraph("Folic acid lowers the risk of neural tube conditions. The neural tube closes in the first few weeks after conception — often before a pregnancy has been confirmed. So the useful window is before you are pregnant, not after you find out."),
            .paragraph("UK guidance is 400 micrograms daily while trying, and through the first twelve weeks. Some people are advised a higher dose, and that is a question for your GP rather than a shelf."),
            .heading("Vitamin D, in this climate"),
            .paragraph("A daily supplement is advised for adults in the UK through autumn and winter, when there is not enough sunlight to make your own. That is general population advice rather than fertility advice, but it applies to you as much as anyone."),
            .heading("The rest, honestly"),
            .bulletList([
                "A varied diet with enough iron matters, particularly if your periods are heavy.",
                "Being significantly under or over weight can affect ovulation, and small sustainable change beats a crash.",
                "Caffeine and alcohol are worth moderating, and the guidance on both is easy to find and dull to follow.",
                "No single food, drink or eating pattern has been shown to make conception happen faster.",
            ]),
            .callout("If you change one thing this month, make it the folic acid. It is cheap, the evidence is strong, and it stops being useful at roughly the moment you find out you needed it."),
        ],
        category: .nutrition,
        tags: ["nutrition", "preconception", "supplements", "folic acid"],
        readingTime: "4 min read",
        heroImage: "learn_hero_preconception",
        featured: false,
        relatedArticleIds: ["a5", "a6", "w10"],
        cta: ArticleCta(type: .openNutrition, label: "Open Nutrition")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 9, 6)
    ),

    LearnArticle(
        id: "w4",
        slug: "cervical-mucus",
        title: "What cervical mucus can tell you",
        excerpt: "The one common fertility sign that predicts rather than confirms — and it costs nothing.",
        body: [
            .paragraph("Cervical fluid changes through the cycle, and the change is not subtle once you know what you are looking at. It is also the only everyday sign that tells you the fertile window is opening rather than closing."),
            .heading("The pattern, roughly"),
            .bulletList([
                "Just after your period: little or nothing, or slightly tacky.",
                "As oestrogen rises: creamy, then wetter, then clearer.",
                "At the most fertile point: clear, slippery and stretchy, often compared to raw egg white.",
                "After ovulation: it dries up or thickens again, usually within a day or two.",
            ]),
            .heading("Why it beats temperature for timing"),
            .paragraph("A temperature rise confirms ovulation has already happened. That is useful for understanding your cycle in hindsight and useless for catching the window. Fluid changes days ahead of the event, which is the part you can act on."),
            .heading("What throws it off"),
            .paragraph("Recent sex, lubricants and some medications all change what you see. So does a cycle where ovulation comes late or does not arrive at all — the pattern can build, fade, and build again."),
            .paragraph("If you never see the wetter, clearer phase across several cycles, that is worth mentioning to a clinician. It is information, not a verdict."),
            .callout("Check at the same point each day and write down what you notice in one word. The vocabulary matters far less than doing it consistently."),
        ],
        category: .tracking,
        tags: ["cycle", "fertile window", "tracking", "cervical mucus"],
        readingTime: "4 min read",
        heroImage: "learn_hero_mucus",
        featured: false,
        relatedArticleIds: ["w1", "w6", "a3"],
        cta: ArticleCta(type: .openLog, label: "Open today's log")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 9, 13)
    ),

    LearnArticle(
        id: "w5",
        slug: "hydration-and-reproductive-health",
        title: "Hydration and reproductive health",
        excerpt: "The real effects are smaller than the marketing and larger than nothing.",
        body: [
            .paragraph("Hydration gets attached to fertility claims it cannot support. It is worth separating what is established from what is merely repeated."),
            .heading("What is established"),
            .bulletList([
                "Cervical fluid is mostly water, so being persistently dehydrated gives your body less to work with.",
                "Mild dehydration measurably affects mood, concentration and perceived effort, which is enough to make a hard month harder.",
                "Thirst is a decent guide for most people, most of the time.",
            ]),
            .heading("What is not"),
            .paragraph("Drinking more water has not been shown to make conception happen faster, to change vaginal pH, or to alter anything about a future pregnancy. Any product suggesting otherwise is charging you for tap water and a story."),
            .heading("A more useful way to think about it"),
            .paragraph("Hydration is a floor, not a lever. Being adequately hydrated removes a small obstacle. Being extraordinarily hydrated does not remove a larger one, and drinking far beyond thirst carries its own risk."),
            .callout("If you are rarely thirsty and your urine is pale, you are fine. Spend the attention you were about to spend on water on your sleep instead."),
        ],
        category: .wellness,
        tags: ["hydration", "wellness", "cycle"],
        readingTime: "3 min read",
        heroImage: "learn_hero_hydration_repro",
        featured: false,
        relatedArticleIds: ["a4", "g5", "w7"],
        cta: ArticleCta(type: .openTrack, label: "Open Hydration")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 9, 20)
    ),

    LearnArticle(
        id: "w6",
        slug: "timing-sex-when-ttc",
        title: "Timing sex when you are trying to conceive",
        excerpt: "Every two to three days, throughout. The elaborate schedules do worse.",
        body: [
            .paragraph("The guidance here is unglamorous and has barely changed in years: sex every two to three days across the cycle gives you the best chance, without anyone having to track anything."),
            .heading("Why regular beats targeted"),
            .paragraph("Aiming at a predicted day assumes the prediction is right. It often is not — ovulation is the most movable part of the cycle. Regular sex means the window is covered whenever it actually opens."),
            .paragraph("It also avoids the failure mode where a couple saves themselves for a date, misses it, and waits another month."),
            .heading("On the elaborate approaches"),
            .paragraph("There is a long tradition of methods promising better odds through precise timing, particular positions, or diet. The evidence for them is weak, and the cost is not neutral: they turn something that should be ordinary into a scheduled performance, and that is its own kind of pressure."),
            .heading("What actually helps"),
            .bulletList([
                "Regular sex spread across the cycle rather than concentrated into two days.",
                "Skipping standard lubricants during the fertile window, or choosing one designed not to interfere.",
                "Not treating a month without a result as a verdict. Most couples take several months.",
            ]),
            .callout("If the schedule is making it worse, drop the schedule. Every two to three days needs no tracking, no tests, and no arguing about what day it is."),
        ],
        category: .tracking,
        tags: ["timing", "fertile window", "cycle", "wellness"],
        readingTime: "3 min read",
        heroImage: "learn_hero_timing",
        featured: false,
        relatedArticleIds: ["w1", "w4", "w11"],
        cta: ArticleCta(type: .openLog, label: "Open today's log")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 9, 27)
    ),

    LearnArticle(
        id: "w7",
        slug: "sleep-stress-and-your-cycle",
        title: "Sleep, stress and your cycle",
        excerpt: "Stress does affect cycles. That is not the same as your cycle being your fault.",
        body: [
            .paragraph("Two things are true at once, and the gap between them is where most of the unhelpful advice lives. Sustained stress and disrupted sleep can affect the hormonal signalling that drives ovulation. And being told to relax has never helped anyone conceive."),
            .heading("What the mechanism actually is"),
            .paragraph("The signal that triggers ovulation starts in the brain. Severe physiological stress — serious illness, extreme exercise, significant undereating, chronic sleep deprivation — can suppress that signal, delaying ovulation or occasionally skipping it. This is a real effect with a real pathway."),
            .paragraph("Ordinary life stress is a different magnitude. It is not established that a difficult few weeks at work will stop you conceiving, and being told it might adds a burden without adding information."),
            .heading("Sleep is the more actionable half"),
            .bulletList([
                "Shift work and habitual short sleep are associated with more cycle irregularity.",
                "Timing appears to matter, not only duration — a consistent schedule beats a long lie-in after a bad week.",
                "Poor sleep also degrades everything you would otherwise use to cope, which is the quieter cost.",
            ]),
            .heading("What to do with this"),
            .paragraph("Treat sleep as the thing you can change and stress as the thing you can manage rather than eliminate. If your cycles have become markedly irregular, raise it with a clinician instead of absorbing it."),
            .callout("Nobody has ever relaxed their way to ovulation on command. Fix the sleep schedule, which is boring, measurable, and actually within reach."),
        ],
        category: .wellness,
        tags: ["sleep", "stress", "wellness", "cycle"],
        readingTime: "4 min read",
        heroImage: "learn_hero_sleep_stress",
        featured: false,
        relatedArticleIds: ["a9", "w5", "w11"],
        cta: ArticleCta(type: .openLog, label: "Log how you slept")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 10, 4)
    ),

    LearnArticle(
        id: "w8",
        slug: "understanding-ovulation-tests",
        title: "Understanding ovulation tests",
        excerpt: "They detect a hormone surge, not an egg — and that distinction explains most of the confusion.",
        body: [
            .paragraph("An ovulation test detects luteinising hormone in urine. LH surges shortly before an egg is released, so a positive test tells you the window is closing rather than opening."),
            .heading("What a positive means"),
            .paragraph("Ovulation usually follows the surge within a day or so. That makes a positive test useful as a last call, and it is why tests pair badly with a strategy of waiting for one before doing anything."),
            .heading("Why they mislead"),
            .bulletList([
                "A surge can happen without an egg being released, so a positive is not proof of ovulation.",
                "Some people surge twice, or have a long low surge the test reads inconsistently.",
                "Testing once a day can miss a short surge entirely.",
                "Some conditions and medications raise baseline LH, producing positives that mean nothing.",
            ]),
            .heading("Using them without being ruled by them"),
            .paragraph("Tests are most useful for learning where in your cycle ovulation tends to fall, over two or three months. Once you know that, they have largely done their job — and regular sex across the window is more reliable than chasing a line."),
            .callout("If a test has ever made you feel you missed your chance for the month, it is working against you. It is a clue about your pattern, not a starting pistol."),
        ],
        category: .tracking,
        tags: ["ovulation", "tracking", "tests", "fertile window"],
        readingTime: "4 min read",
        heroImage: "learn_hero_ovulation_tests",
        featured: false,
        relatedArticleIds: ["w1", "w4", "w6"],
        cta: ArticleCta(type: .openTrack, label: "Open your cycle")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 10, 11)
    ),

    LearnArticle(
        id: "w9",
        slug: "supporting-sperm-health",
        title: "Supporting sperm health",
        excerpt: "Half the equation, most of the silence, and a three-month lag on anything you change.",
        body: [
            .paragraph("Around half of difficulty conceiving involves a male factor, and it is the half that tends to get investigated last. It is also the half where lifestyle change has a clear timeline."),
            .heading("The three-month lag"),
            .paragraph("Sperm take roughly two to three months to develop. Anything changed today shows up in a test around a season later. That cuts both ways: a bad month is not permanent, and a good week is not a result."),
            .heading("What has reasonable evidence"),
            .bulletList([
                "Stopping smoking, which affects both count and motility.",
                "Reducing heavy alcohol intake.",
                "Managing weight, since obesity is associated with lower counts.",
                "Avoiding sustained heat — hot tubs, saunas, and a laptop resting where you would expect.",
                "Treating anabolic steroid use as directly relevant, because it suppresses production and the effect can outlast the use.",
            ]),
            .heading("What is oversold"),
            .paragraph("The supplement market here is large and the evidence is thin. Some antioxidant formulations show small effects in some studies. None is established enough to justify what they cost."),
            .heading("Getting it tested"),
            .paragraph("A semen analysis is quick, non-invasive and available through a GP. NHS guidance is to see a GP after a year of trying, and sooner if the woman is 36 or over. When you go, both partners should be assessed rather than one."),
            .callout("If only one of you is being tracked, measured and supplemented, the investigation is running at half strength."),
        ],
        category: .wellness,
        tags: ["sperm health", "partner", "wellness", "preconception"],
        readingTime: "4 min read",
        heroImage: "learn_hero_sperm_health",
        featured: false,
        relatedArticleIds: ["w11", "w3", "w10"],
        cta: ArticleCta(type: .openLog, label: "Open today's log")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 10, 18)
    ),

    LearnArticle(
        id: "w10",
        slug: "fertility-supplements-explained",
        title: "Fertility supplements, and what the evidence says",
        excerpt: "Two have real evidence behind them. The rest are priced as though they do.",
        body: [
            .paragraph("Walk into any pharmacy and the conception shelf will offer you a dozen blends at several times the price of their components. It is worth knowing which parts are doing the work."),
            .heading("The two worth the money"),
            .bulletList([
                "Folic acid, 400 micrograms daily while trying and through the first twelve weeks. Strong evidence, trivial cost.",
                "Vitamin D, 10 micrograms daily through UK autumn and winter. General health advice that happens to apply to you.",
            ]),
            .heading("The rest, briefly"),
            .paragraph("Coenzyme Q10, inositol, omega-3s and assorted antioxidant blends appear in most conception formulas. Some have promising early research, usually in specific groups rather than the general population. None has evidence approaching that for folic acid, and none should be bought on the strength of its packaging."),
            .paragraph("Inositol is the most likely exception if you have PCOS, and that is a conversation with a clinician rather than a shelf decision."),
            .heading("What to watch for"),
            .bulletList([
                "Blends where an active ingredient appears at a dose far below the one that was studied.",
                "Vitamin A, which should be avoided at high doses when trying to conceive.",
                "Any product implying it improves your odds by a specific amount. That claim is not supportable.",
                "Herbal preparations sold as cycle regulators, which are not tested to the same standard and can interact with medication.",
            ]),
            .callout("Buy the folic acid, buy the vitamin D, and put what you were going to spend on the blend towards something that will actually improve your month."),
        ],
        category: .nutrition,
        tags: ["supplements", "nutrition", "preconception", "evidence"],
        readingTime: "5 min read",
        heroImage: "learn_hero_supplements_evidence",
        featured: false,
        relatedArticleIds: ["a6", "w3", "w9"],
        cta: ArticleCta(type: .openNutrition, label: "Open Nutrition")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 10, 25)
    ),

    LearnArticle(
        id: "w11",
        slug: "when-to-ask-for-support",
        title: "When to ask for fertility support",
        excerpt: "There is a threshold, it is earlier than most people think, and waiting past it costs you options.",
        body: [
            .paragraph("Most couples conceive within a year. That statistic is meant to reassure, and it does — but it also gets used to talk people out of asking for help at exactly the point where asking becomes useful."),
            .heading("The thresholds"),
            .bulletList([
                "Trying for twelve months without success: see your GP. That is the standard NHS threshold.",
                "Aged 36 or over: see your GP sooner rather than waiting out the year. The shorter window is deliberate.",
                "At any point, if your cycles are very irregular or absent, if you have known endometriosis or PCOS, if you have had pelvic surgery or treatment for cancer, or if either of you is already aware of a fertility problem — go now rather than waiting out the clock.",
            ]),
            .heading("Why waiting is not neutral"),
            .paragraph("Investigation takes time. Referral takes time. Treatment takes time, and eligibility criteria in many areas are tied to age. Six months of waiting to see whether it resolves can quietly become eighteen by the time anyone is doing anything."),
            .heading("What the first appointment is like"),
            .paragraph("Mostly conversation and basic tests: blood tests to check ovulation, a semen analysis, questions about your cycles and history. It is not a commitment to treatment, and it is not a failure. Both partners should be seen."),
            .heading("Bringing your log"),
            .paragraph("Several months of cycle dates, symptoms and readings is genuinely useful to a clinician, and far more reliable than trying to recall it in the room. That is the most practical thing this app can do for you here."),
            .callout("If you have hit the threshold, book the appointment. You can always cancel it. What you cannot do is get the months back."),
        ],
        category: .wellness,
        tags: ["support", "clinician", "wellness", "cycle"],
        readingTime: "5 min read",
        heroImage: "learn_hero_support",
        featured: false,
        relatedArticleIds: ["w9", "w1", "a10"],
        cta: ArticleCta(type: .openInsights, label: "Open Insights")!,
        disclaimerRequired: true,
        publishedAt: CalendarDate(2026, 11, 1)
    ),
]
